services:
  soundbuttons:
    build:
      context: .
      target: final
      args:
        - BUILD_CONFIGURATION=Release
      # cache_from:
      #   - ghcr.io/recorder-moe/soundbuttons:cache
      # cache_to:
      #   - type=inline
    ports:
      - 7071:8080
    env_file:
      - path: .env
        required: false
    environment:
      # This connect to the azure storage emulator
      # https://learn.microsoft.com/zh-tw/azure/storage/common/storage-use-azurite#well-known-storage-account-and-key
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-emulator:10000/devstoreaccount1;QueueEndpoint=http://azurite-emulator:10001/devstoreaccount1;TableEndpoint=http://azurite-emulator:10002/devstoreaccount1;
      # #
      # - Seq_ServerUrl=
      # - Seq_ApiKey=
      # - AzureStorage=
      # - OpenAI_ApiKey=

  # Azure Storage Emulator, needed for the durable functions
  # You can use your online azure storage account instead and make sure to set the AzureWebJobsStorage env variable to the online connection string
  azurite-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
